spring:
  datasource:
    url: jdbc:postgresql://dpg-d16hkiod13ps739d5vpg-a.oregon-postgres.render.com:5432/umeumesweets_db?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

google:
  api:
    key: ${GOOGLE_API_KEY}

kakao:
  map:
    api-key: ${KAKAO_MAP_API_KEY}
