spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umeume?serverTimezone=Asia/Seoul
    username: root
    password: ume1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

google:
  api:
    key: AIzaSyAMGwHFx3w-S8x96aP6aM9mqKtopz8UBh8

kakao:
  map:
    api-key: b6fc6ee40c6ed118d4c005a621698e5a
